### ISSUE TITLE
Losing data

### ISSUE THREAD

**Issue by ivanjaros** [kettek/apng#12]
I am converting gif into apng and I am observing loss of data. Something with color palette not translating properly?

This is irfanview showing original gif above and converted apng below. 
![obrázok](https://github.com/user-attachments/assets/66b1e157-e53b-4bc4-b6d6-926e32529a10)

random gif from the web:
![src2](https://github.com/user-attachments/assets/04637ade-0a2e-4267-95a1-72d1bc50f8ad)

converted into apng:
![dst2](https://github.com/user-attachments/assets/ee087600-ced1-4384-aea9-a88acedfc4fe)

The code:
```go
	g, err := gif.DecodeAll(src)
	if err != nil {
		return err
	}

	out := apng.APNG{
		Frames:    make([]apng.Frame, len(g.Image)), // note the filled slice
		LoopCount: uint(g.LoopCount),
	}

	for k := range g.Image {
		out.Frames[k].Image = g.Image[k]
		out.Frames[k].IsDefault = k == 0
		out.Frames[k].DelayDenominator = uint16(g.Disposal[k]) * 100
		out.Frames[k].DelayNumerator = uint16(g.Delay[k])
	}

	return apng.Encode(dst, out)
```

**Comment by ivanjaros** [comment]
If i remove the isDefault, I will get 24B
![obrázok](https://github.com/user-attachments/assets/6476a63b-45b6-44cf-b9bf-78c136b52ec2)

 and this result:

![dst3](https://github.com/user-attachments/assets/1f2804e8-5288-4f45-87ab-b7e6c087978c)

**Comment by kettek** [comment]
DisposeOp might have to echo the GIF's Dispose for corresponding frames... I believe there is a slice containing that information in the returned *GIF. I'll investigate when I can, otherwise.

**Comment by ivanjaros** [comment]
I figured it out. Once i removed the default frame setting and tried combining the "ops", this one works as desired:
![obrázok](https://github.com/user-attachments/assets/397eed63-ab6c-4480-bfc6-413b740d488e)
