### ISSUE TITLE
Encoding RGBA Frames is opaque

### ISSUE THREAD

**Issue by kettek** [kettek/apng#2]
Following from #1, the encoding of frames that are RGBA turn opaque if the first frame is considered as opaque. This is due to how the standard PNG library detected RGBA vs RGB colors by checking to see if any pixels in the image were not opaque and marking it as such. If they were all opaque, then the image was to be considered as non-alpha. This can be seen in @Lucki's re-encoded image [here](https://github.com/kettek/apng/issues/1#issuecomment-551655263).

Pending further testing, fixes have been implemented and will be committed shortly.

**Comment by kettek** [comment]
@Lucki, I have committed the changes that should fix your re-encoding problem. Please let me know if there are any issues for you.

**Comment by Lucki** [comment]
No issues anymore, thanks!

**Comment by kettek** [comment]
Excellent.

Closed by 414630eed80f58556578d58f0d7bd8ca70650e84
